apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensureNameSpace
spec:
  validationFailureAction: enforce
  rules:
  - name: check-ns-purpose-label
    match:
      any:
      - resources:
          kinds:
          - Namespace
    validate:
      message: "You must have namespace called devsecops_project."
      pattern:
        metadata:
          labels:
            namespace: devsecops_project